# Generated by Django 5.2.6 on 2025-10-09 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGA', 'Operador de Bodega'), ('COMPRAS', 'Operador de Compras'), ('VENTAS', 'Operador de Ventas'), ('PRODUCCION', 'Jefe de Producción')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
