# Generated by Django 5.2.5 on 2025-09-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
