# Generated by Django 5.2.5 on 2025-10-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_module_role_alter_perfil_rol_rolemodulepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='mfa_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sesiones_activas',
            field=models.IntegerField(default=0),
        ),
    ]
