# Generated by Django 5.2.5 on 2025-10-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_estado_perfil_mfa_habilitado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='area',
        ),
    ]
