# Generated by Django 5.2.5 on 2025-09-25 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('idOrdenProduccion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinalizacion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('idConsumo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('merma', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='productos.producto')),
                ('ordenProduccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='produccion.ordenproduccion')),
            ],
        ),
    ]
