# Generated by Django 4.2.26 on 2025-11-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la bodega', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('responsable', models.CharField(help_text='Nombre del encargado', max_length=100)),
                ('capacidad_maxima', models.IntegerField(default=0, help_text='Capacidad en unidades')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SECUNDARIA', 'Secundaria'), ('TRANSITO', 'Tránsito')], default='SECUNDARIA', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['nombre'],
            },
        ),
    ]
