# Generated by Django 5.2.6 on 2025-10-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('precioBase', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('idLote', models.AutoField(primary_key=True, serialize=False)),
                ('fechaIngreso', models.DateTimeField()),
                ('fechaVencimiento', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=45)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('idCosto', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaCosto', models.DateTimeField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
