# Generated by Django 5.2.6 on 2025-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioBase',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='producto',
            name='lote',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('GALLETAS', 'Galletas'), ('CHOCOLATES', 'Chocolates'), ('ALFAJORES', 'Alfajores'), ('CONFITERIA', 'Confitería')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Costo',
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
