# Generated by Django 5.2.6 on 2025-10-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='bajo_stock',
            field=models.BooleanField(default=False),
        ),
    ]
