# Generated by Django 5.2.6 on 2025-10-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_bajo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alto_stock',
            field=models.BooleanField(default=False),
        ),
    ]
