# Generated by Django 5.2.6 on 2025-10-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_alto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='alto_stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='bajo_stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
    ]
