# Generated by Django 5.2.6 on 2025-10-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_producto_alto_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.CharField(choices=[('ALTO', 'Alto'), ('BAJO', 'Bajo')], default='ALTO', max_length=10),
        ),
    ]
