# Generated by Django 4.2.26 on 2025-11-09 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('transacciones', '0002_movimientoinventario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='bodegas.bodega'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='bodegas.bodega'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('VENTA', 'Venta'), ('TRANSFERENCIA', 'Transferencia entre bodegas')], max_length=20),
        ),
    ]
