# Generated by Django 4.2.26 on 2025-11-10 05:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_movimientoinventario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='doc_referencia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='manejo_lotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='manejo_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='perecible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='serie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transacciones.bodega'),
        ),
    ]
