# Generated by Django 5.2.6 on 2025-10-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_proveedor_activo_alter_proveedor_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='activo',
            new_name='marcar_activo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='estado',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='marcar_inactivo',
            field=models.BooleanField(default=False),
        ),
    ]
