# Generated by Django 5.2.6 on 2025-10-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_rename_activo_proveedor_marcar_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='condiciones_pago',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='marcar_activo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='marcar_inactivo',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
    ]
