# Generated by Django 5.2.6 on 2025-10-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_remove_proveedor_condiciones_pago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='estado',
            new_name='stock',
        ),
    ]
