# Generated by Django 5.2.6 on 2025-10-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_rename_estado_proveedor_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='stock',
            new_name='estado',
        ),
    ]
